// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPd2FjTKE5cNRt_vASOgrja-ii4ctq0lk',
    appId: '1:559226531566:web:cc28843e2d20f8d4c00dff',
    messagingSenderId: '559226531566',
    projectId: 'taskly-9f9bd',
    authDomain: 'taskly-9f9bd.firebaseapp.com',
    storageBucket: 'taskly-9f9bd.firebasestorage.app',
    measurementId: 'G-4RH7MEPD8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUGf0a2tVADa5jk-H07lS5JaF5LevS8E',
    appId: '1:559226531566:android:5610deba12e40a6dc00dff',
    messagingSenderId: '559226531566',
    projectId: 'taskly-9f9bd',
    storageBucket: 'taskly-9f9bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0M-qZF0eb-nCvMTMjwNMpSOjbPeqQY8',
    appId: '1:559226531566:ios:199e7bf3df092314c00dff',
    messagingSenderId: '559226531566',
    projectId: 'taskly-9f9bd',
    storageBucket: 'taskly-9f9bd.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0M-qZF0eb-nCvMTMjwNMpSOjbPeqQY8',
    appId: '1:559226531566:ios:199e7bf3df092314c00dff',
    messagingSenderId: '559226531566',
    projectId: 'taskly-9f9bd',
    storageBucket: 'taskly-9f9bd.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPd2FjTKE5cNRt_vASOgrja-ii4ctq0lk',
    appId: '1:559226531566:web:b58114c6f01009dfc00dff',
    messagingSenderId: '559226531566',
    projectId: 'taskly-9f9bd',
    authDomain: 'taskly-9f9bd.firebaseapp.com',
    storageBucket: 'taskly-9f9bd.firebasestorage.app',
    measurementId: 'G-D0LPCFW7GV',
  );
}
